#########################################################################
#         _            _ _                  ___  ___  ___ _____ _____   #
#        (_)          | (_)                 |  \/  | / _ \_   _/  ___|  #
#   _ __  _ _ __   ___| |_ _ __   ___   _ __| .  . |/ /_\ \| | \ `--.   #
#  | '_ \| | '_ \ / _ \ | | '_ \ / _ \ | '__| |\/| ||  _  || |  `--. \  #
#  | |_) | | |_) |  __/ | | | | |  __/ | |  | |  | || | | || | /\__/ /  #
#  | .__/|_| .__/ \___|_|_|_| |_|\___| |_|  \_|  |_/\_| |_/\_/ \____/   #
#  | |     | |                     ______                               #
#  |_|     |_|                    |______|                              #
#                                                                       #
#########################################################################


###############################################################
# the genome to use (UCSC convention)
###############################################################
genome_dir: /shared/sudlab1/General/mirror/genomes/plain
genome: hg38_noalt.fasta

gtf:
    path: /shared/sudlab1/utrons/Cell_lines/CCLE/ccle_utrons/agg-agg-agg_unzipped.gtf

star_index: /shared/sudlab1/General/mirror/genomes/STAR/hg38_noalt_junc85_99.dir

###############################################################
# Location of annotation database
###############################################################
annotations:
    database: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85/csvdb

    # directory with annotation information
    dir: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85

###############################################################
# Information about reads
###############################################################
reads:
        #are they paired or single, if paired state TRUE, if single state FALSE
        paired: FALSE
        #how long are they? Can check with 
        # samtools view FILE.bam | head -n 1000000 | cut -f 10 | perl -ne 'chomp;print length($_) . "\n"' | sort | uniq -c
        length: 50
        

###############################################################
# rMATS configuration
###############################################################
rmats:
    # Paired mode
    paired: FALSE
    # If paired mode is true, make sure the pairing identifier is in the first block before - 
    # e.g. ID123-Day0-R0.bam, ID123-Day5-R0.bam
    # Should RMATS look for novel splice sites?
    detect_novel_ss: FALSE
    #If TRUE, what should its criteria be on introns?
    min_intron_length: 50
    max_intron_length: 2500


